logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: DEBUG
    org.opensaml.xmlsec: DEBUG

spring:
  security:
    saml2:
      relyingparty:
        registration:
          samlexample:                                                #registration id
            acs:
              location: "{baseUrl}/custom/{registrationId}"          #enable for localhost
#              location: "https://{baseHost}/custom/{registrationId}"  #enable for AWS
            entity-id: poc-spring-boot-docker-local                   #enable for local, replace its.com with <team name>.com  
#            entity-id: poc-spring-boot-docker                         #enable for AWS, replace its.com with <team name>.com
            signing:
              credentials:
                - private-key-location: "classpath:credentials/private.key"
                  certificate-location: "classpath:credentials/public.cer"
            identityprovider:
              singlesignon:
                sign-request: false
              entity-id: https://samltest.id/saml/idp
              metadata-uri: https://samltest.id/saml/idp